[package]
name = "futures-udp"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "Non-blocking async UDPSocket, Stream & Sink. Runtime agnostic: works with tokio & futures-rs. Minimal dependencies."
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
keywords = ["async", "udp", "net"]
homepage = "https://github.com/MusicalNinjaDad/futures-udp"
repository = "https://github.com/MusicalNinjaDad/futures-udp"
categories = ["asynchronous", "network-programming"]
license = "MIT"
rust-version = "1.90.0"

[dependencies]
futures = { version = "0.3.32", default-features = false }
futures-net = { version = "0.6.0", default-features = false }

# feature "all" enables the call to `nonblocking`, which is unavailable on some platforms.
# That call is gated in our code.
# Make sure to temporarily remove "all", check for new failure sites and gate them appropriately
# when changing any code calling socket2 functionality.
socket2 = { version = "0.6.3", features = ["all"] }

[dev-dependencies]
futures = { version = "0.3.32", features = ["async-await"] }
futures-net = { version = "0.6.0", default-features = true }

[build-dependencies]
build_safely = "0.5.2"

[patch.crates-io]
build_safely = { git = "https://github.com/MusicalNinjaDad/build_safely", branch = "bool_to_result" }
